package com.shxiaj.ssm.pojo;

import java.util.Date;

public class Photo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_photo.id
     *
     * @mbggenerated Wed Jun 29 00:55:01 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_photo.filename
     *
     * @mbggenerated Wed Jun 29 00:55:01 CST 2022
     */
    private String filename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_photo.creat_date
     *
     * @mbggenerated Wed Jun 29 00:55:01 CST 2022
     */
    private Date creatDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_photo.id
     *
     * @return the value of t_photo.id
     *
     * @mbggenerated Wed Jun 29 00:55:01 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_photo.id
     *
     * @param id the value for t_photo.id
     *
     * @mbggenerated Wed Jun 29 00:55:01 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_photo.filename
     *
     * @return the value of t_photo.filename
     *
     * @mbggenerated Wed Jun 29 00:55:01 CST 2022
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_photo.filename
     *
     * @param filename the value for t_photo.filename
     *
     * @mbggenerated Wed Jun 29 00:55:01 CST 2022
     */
    public void setFilename(String filename) {
        this.filename = filename == null ? null : filename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_photo.creat_date
     *
     * @return the value of t_photo.creat_date
     *
     * @mbggenerated Wed Jun 29 00:55:01 CST 2022
     */
    public Date getCreatDate() {
        return creatDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_photo.creat_date
     *
     * @param creatDate the value for t_photo.creat_date
     *
     * @mbggenerated Wed Jun 29 00:55:01 CST 2022
     */
    public void setCreatDate(Date creatDate) {
        this.creatDate = creatDate;
    }

    public Photo(Integer id, String filename, Date creatDate) {
        this.id = id;
        this.filename = filename;
        this.creatDate = creatDate;
    }

    public Photo() {
    }

    @Override
    public String toString() {
        return "Photo{" +
                "id=" + id +
                ", filename='" + filename + '\'' +
                ", creatDate=" + creatDate +
                '}';
    }
}